# Generated by Django 5.2.3 on 2025-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='products/thumbnails/default.jpg', upload_to='products/thumbnails/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
